// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQVQPOOOOQO'#C^'#C^OOQO'#Ce'#CeQVQPOOOOQO-E6c-E6c",
  stateData: "k~O[OS~ORPOSPOTPOUPOVPOWPO~O",
  goto: "eYPPZPPPPPP_TQORQRORSR",
  nodeNames: "⚠ Program Statement Keyword Number Operator LineComment Identifier Parens",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ")}~R^qr}st!Sxy!}yz!}z{}{|}}!O}!P!Q}!^!_}!_!`}!`!a}!}#O#S#W#X'k#`#a)k~!SOT~~!VP!}#O!Y~!]P#Q#R!`~!cP#O#P!f~!iP#b#c!l~!oP#P#Q!r~!uPz{!x~!}OU~~#SOW~~#VRpq#`!Q!R$g#T#U%U~#cP#O#P#f~#iP#h#i#l~#oP#O#P#r~#uP#f#g#x~#{P#O#P$O~$RP#b#c$U~$XP#P#Q$[~$_P{|$b~$gO[~~$jP}!O$m~$pP!Z![$s~$vP#P#Q$y~$|P{|%P~%UOS~~%XP}!O%[~%_P#n#o%b~%eP!c!d%h~%kP}!O%n~%qP!|!}%t~%wP#P#Q%z~%}P!}#O&Q~&TP#T#U&W~&ZP}!O&^~&aP#n#o&d~&gP!c!d&j~&mP}!O&p~&sP!|!}&v~&yP!Q!R&|~'PP}!O'S~'VP!Z!['Y~']P#P#Q'`~'cPz{'f~'kOV~~'nQ#U#V't#f#g'y~'yOR~~'|P#c#d(P~(SP#d#e(V~(YP#R#S(]~(`P#T#U(c~(fP#`#a(i~(lP#`#a(o~(rP#R#S(u~(xP#h#i({~)OP#T#U)R~)UP#U#V)X~)[P#`#a)_~)bP#X#Y)e~)hP#g#h't~)nP#c#d)q~)tP#T#U)w~)zP#W#X't",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
