// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  Keyword = 3,
  Number = 4,
  Operator = 5,
  LineComment = 6,
  Identifier = 7,
  Parens = 8
